<!-- Contains required properties for osu!framework projects. -->
<Project>
  <PropertyGroup>
    <ApplicationManifest>$(MSBuildThisFileDirectory)app.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Label="Documentation">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
