// Tests for EditorChart: event firing, ApplyDefaults, nested regeneration, deselect-on-remove, time ordering.
// Plain NUnit — no game host required.

using System.Linq;
using Garbus.Game.Charts;
using Garbus.Game.Edit;
using Garbus.Game.Objects;
using NUnit.Framework;

namespace Garbus.Game.Tests.Editor
{
    [TestFixture]
    public class TestEditorChart
    {
        private EditorChart chart = null!;

        [SetUp]
        public void SetUp() => chart = new EditorChart(new GarbusChart());

        [Test]
        public void TestAddFiresEventAndAppliesDefaults()
        {
            GarbusHitObject? added = null;
            chart.HitObjectAdded += h => added = h;
            var hold = new HoldNote { StartTime = 1000, AngleDeg = 90, Duration = 500 };
            chart.Add(hold);
            Assert.That(added, Is.SameAs(hold));
            Assert.That(hold.NestedHitObjects, Is.Not.Empty); // head generated by ApplyDefaults
            Assert.That(chart.HitObjects, Has.Count.EqualTo(1));
        }

        [Test]
        public void TestUpdateRegeneratesNested()
        {
            var hold = new HoldNote { StartTime = 1000, AngleDeg = 90, Duration = 500 };
            chart.Add(hold);
            var headBefore = hold.NestedHitObjects.Single();
            hold.Duration = 900;
            chart.Update(hold);
            Assert.That(hold.NestedHitObjects.Single(), Is.Not.SameAs(headBefore));
        }

        [Test]
        public void TestRemoveDeselects()
        {
            var note = new CardinalNote { StartTime = 0, AngleDeg = 0 };
            chart.Add(note);
            chart.SelectedHitObjects.Add(note);
            chart.Remove(note);
            Assert.That(chart.SelectedHitObjects, Is.Empty);
        }

        [Test]
        public void TestHitObjectsStayTimeOrdered()
        {
            chart.Add(new CardinalNote { StartTime = 2000, AngleDeg = 0 });
            chart.Add(new CardinalNote { StartTime = 1000, AngleDeg = 0 });
            Assert.That(chart.HitObjects.Select(h => h.StartTime), Is.Ordered);
        }

        /// <summary>
        /// Regression: EditorChart.Add/Remove must write through to Chart.HitObjects so that
        /// serialization (Save) sees every edit — not just the shadow list.
        /// </summary>
        [Test]
        public void TestAddWritesThroughToChartHitObjects()
        {
            var note1 = new CardinalNote { StartTime = 0, AngleDeg = 0 };
            var note2 = new CardinalNote { StartTime = 500, AngleDeg = 90 };

            chart.Add(note1);
            chart.Add(note2);

            // The underlying chart's list must be identical in content and order.
            Assert.That(chart.Chart.HitObjects, Is.EqualTo(chart.HitObjects));
            Assert.That(chart.Chart.HitObjects, Has.Count.EqualTo(2));
            Assert.That(chart.Chart.HitObjects[0], Is.SameAs(note1));
            Assert.That(chart.Chart.HitObjects[1], Is.SameAs(note2));
        }

        [Test]
        public void TestRemoveWritesThroughToChartHitObjects()
        {
            var note1 = new CardinalNote { StartTime = 0, AngleDeg = 0 };
            var note2 = new CardinalNote { StartTime = 500, AngleDeg = 90 };

            chart.Add(note1);
            chart.Add(note2);
            chart.Remove(note1);

            Assert.That(chart.Chart.HitObjects, Is.EqualTo(chart.HitObjects));
            Assert.That(chart.Chart.HitObjects, Has.Count.EqualTo(1));
            Assert.That(chart.Chart.HitObjects[0], Is.SameAs(note2));
        }
    }
}
